### ISSUE TITLE
NN objective function for AM  label:question 

### ISSUE THREAD

**Issue by FelixArticae** [ymlasu/Neural-Optimization-Machine-NOM-#1]
Hello, 
after thoroughly reviewing the repository, I've noticed that the "AM" folder lacks the code associated with the AM related to the NN_objective function, unlike in the other examples where both the model and the code are provided. In this case, only the saved model is included. I believe that incorporating the corresponding code would significantly enhance the example, offering a more comprehensive understanding of the main concepts underpinning this research. Providing the code alongside the saved model will not only aid in replicating and understanding the implementation but also serve as a valuable resource for those delving into the intricacies of the NN_objective function within the context of AM. Your consideration of including this code would be greatly appreciated.

**Comment by jcj7292** [comment]
> Hello, after thoroughly reviewing the repository, I've noticed that the "AM" folder lacks the code associated with the AM related to the NN_objective function, unlike in the other examples where both the model and the code are provided. In this case, only the saved model is included. I believe that incorporating the corresponding code would significantly enhance the example, offering a more comprehensive understanding of the main concepts underpinning this research. Providing the code alongside the saved model will not only aid in replicating and understanding the implementation but also serve as a valuable resource for those delving into the intricacies of the NN_objective function within the context of AM. Your consideration of including this code would be greatly appreciated.

Thank you for your through review. The NN_objective function related to AM can be found in https://github.com/jcj7292/AM-PPgNN

**Comment by FelixArticae** [comment]
Thank you for your quick answer, and the information provided.

Best Regards, Félix.
